### ISSUE TITLE
Subordinate action not working correctly when trigger is a WDateField

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#452] opened 2016-03-18 03:58 UTC
If I have a WDateField as aSubordinateTrigger and a WField as its Subordinate target. With an Equals 'null' condition, and actions of Show and Hide. When I enter a date the WField is shown, then when I clear the Date using the little x in the date field the text area is not hidden. #

**Comment by marksreeves** [comment] 2016-03-20 21:42
@ricksbrown would you have time to look at this? I am completely swamped this week, and it would be nice to get it fixed before we make the next release. If you are also fully committed I will try to get to it.

This issue has been kicking around for some time. It is caused by the dual nature of WDateField's value in that has two values when our useless browser fill is in place: the text in the input and the yyyy-mm-dd value. 

There is a workaround which is to use a RegExp subordinate comparator but we should fix this so that a "null" (i.e. empty string) value works as expected.

**Comment by marksreeves** [comment] 2016-03-22 06:18
Looks like a missing assignment on line 451 of wc/ui/subordinate.js. @ricksbrown have you had a chance to look at this? If not I can take it over tonight.

**Comment by ricksbrown** [comment] 2016-03-22 06:22
@marksreeves sorry I have not started yet - was planning to look at it tomorrow - feel free to assign to yourself if you have capacity.

**Closed** 2016-03-22 08:32 UTC
Labels: bug
