### ISSUE TITLE
Investigate and fix XSLT Issues Detected by IntelliJ

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#583] opened 2016-05-04 06:18 UTC
Seems XSLT engines are more forgiving than I would have imagined. 

IntelliJ has powerful tools for analyzing XSLT which detect issues not found by any other tool I have tried (including Oxygen).

A spot check of some of these issues leads me to believe that IntelliJ is correct. I'm too scared to fix these in 1.1.x 
I'm thinking maybe 1.2.

The list of issues can be produced in IntelliJ like so:

`Analyze > Run Inspection by Name...` then type something like `xsl` or `xml`

I found the `Template Invocation Problems` results quite interesting, for example.

Kudos to IntelliJ.

**Comment by marksreeves** [comment] 2016-05-05 07:31
Did you happen to use an XSLT 2 processor in IntelliJ? It has some quite rigid rules which are not terribly relevant in XSLT 1.

**Comment by ricksbrown** [comment] 2016-05-06 03:43
My hope is that IntelliJ is smart enough to honor the `version` attribute on the `xsl:stylesheet` element but yeah it's something to watch out for... I can't see any way of manually choosing the XSLT version.

An example issue it detects is the "undeclared template parameter `space`" in [wc.ui.text.text_space.xsl](https://github.com/BorderTech/wcomponents/blob/799c9f17db64cb1a617003b9308e75c44db2a203/wcomponents-theme/src/main/xslt/wc.ui.text.text_space.xsl#L22) which calls the template [wc.ui.text.n.WStyledTextContent.xsl](https://github.com/BorderTech/wcomponents/blob/799c9f17db64cb1a617003b9308e75c44db2a203/wcomponents-theme/src/main/xslt/wc.ui.text.n.WStyledTextContent.xsl#L9) that seriously looks to me like it doesn't have a `space` parameter...

There are over one hundred other such issues detected on this analysis alone.

**Comment by marksreeves** [comment] 2016-05-06 03:53
Yep, that'd be me. I cut a pile of guff from those templates quite a while ago (1.1.0 I think) so it is likely I left a param lying about. I will take a look.

**Comment by marksreeves** [comment] 2016-05-09 03:33
Apart from the item fixed in #587 the "errors" reported in IntelliJ are **all** false negatives.

1. There are a number of "errors" of description `expected type 'nodeset', got 'string'` but investigation of these indicates that the type is correct (refer to http://www.w3.org/TR/xpath/#NT-Expr)
2. There are a number of "errors" involving optional params which are caused by an unfounded assumption in IntelliJ which omits the default value of any xsl param is an empty string. See [XSLT transformations Section 11.2](http://www.w3.org/TR/xslt#variable-values):

  > If the variable-binding element has empty content and does not have a select attribute, then the value of the variable is an empty string. Thus
  `<xsl:variable name="x"/>`
  >
  > is equivalent to
  >
  > `<xsl:variable name="x" select="''"/>`
 
Therefore this issue was actually fixed by #587.

**Closed by marksreeves** 2016-05-09 03:33 UTC
