### ISSUE TITLE
Subordinates should be able to set input values

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#643] opened 2016-05-24 00:12 UTC
As the title says subordinates should be able to set input values. Because they cannot it results in excessive use of ajax controls. A project I am working on would be able to replace much of its ajax controls with subordinates if they could set values. Providing users with a much better user experience

@jonathanaustin @Joshua-Barclay @ricksbrown @marksreeves

**Comment by marksreeves** [comment] 2016-05-25 23:37
Duplicate of #260

**Closed by marksreeves** 2016-05-25 23:37 UTC
Labels: duplicate
