### ISSUE TITLE
Enhancement request: WToggleButton to show/hide a component

### ISSUE THREAD

**Issue by SonjaG** [BorderTech/wcomponents#555] opened 2016-04-18 06:26 UTC
Are you able to provide a WToggleButton that shows/hides a component? Like a WCheckBox that looks like a button. For example "add address" button shows the address fields on a component that also has a "remove address" button that hides it again.

**Comment by marksreeves** [comment] 2016-04-18 06:47
Two buttons or one toggle button? Is it a "checkbox" or a "pair of radio buttons?" 

The difference is that a single toggle button would be independent and would not change the state of another toggle button. Perhaps the original requester wants a group of toggle buttons?

**Comment by SonjaG** [comment] 2016-04-26 00:09
UNCLASSIFIED
Two buttons that sit on the same spot on the page and either shows or hides a section. Consider the scenario of capturing an address as additional information to education/employment. By default the address fields are hidden (some are mandatory) and an "add address" button is visible. This button should then show the address section which includes a "remove address" button. It should also hide itself. Note that I've got the additional requirement to show/hide the address section if a status dropdown changes to future. One tricky bit is that the user could have first clicked add address button, then changed the dropdown to something that could hide the address section. It would be nice if the add address would deactivate this dropdown subordinate control so that the address section  would remain. But this is complex to do, so if it can't be done for the next release, we can put it as a separate enhancement request.

I'd be glad to talk about it more...

**Comment by marksreeves** [comment] 2016-04-28 08:21
@jonathanaustin Any input into when we can schedule this?

**Comment by marksreeves** [comment] 2016-06-23 14:42
Duplicate of #428

**Closed by marksreeves** 2016-06-23 14:42 UTC
Labels: enhancement
