### ISSUE TITLE
Use the correct HTTP response code

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#341] opened 2016-01-26 22:06 UTC
When the session has expired on the server it is possible that the user may still trigger AJAX requests.
Currently the server responds to these with a message like so:

```
The system is currently unavailable.

```
Which is fine and dandy EXCEPT the response code is `HTTP/1.1 200 OK` which is the wrong code for a session timeout.

@jonathanaustin please fix.

**Comment by marksreeves** [comment] 2016-01-28 07:07
Added this to the next milestone but it should be fixed sooner if possible.

**Comment by jonathanaustin** [comment] 2016-03-17 10:12
Is this happening in the latest release? I cant seem to recreate it.

We did make some changes back in WComponent14 to fix a lot of these response codes. Especially in the AJAX space.

**Comment by marksreeves** [comment] 2016-03-17 22:52
This occurs only when uploading a file.

Steps to reproduce:

1. start an lde with a sensibly short session (maybe 60 seconds - it has to be long enough to get to the example);
2. open the example "Form controls" > "Multi file Ajax";
3. open a network monitor such as Chrome's dev tools;
4. wait for your session to time out;
5. drag a file into the upload tool;
6. when the editor dialog opens just click the save button, this is not the important bit;
7. get an error;
8. see we have a 200 with the excellent message "The system is currently unavailable".

**Comment by jonathanaustin** [comment] 2016-03-21 01:02
This is happening due to WServlet not handling multi part AJAX requests.

WComponents looks for particular request parameters to determine if a request is an ajax request. As it was not handling multi part forms, it was not reading the ajax parameter and treating the request as a normal "page" request.

Have changed WServlet to process the multi part requests earlier in the request.

Have also tightened up the com.github.bordertech.wcomponents.Request interface for the return type of getParameters and getFiles.

**Closed** 2016-03-21 01:39 UTC
Labels: bug
