### ISSUE TITLE
WButton Ajax Issue

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#457] opened 2016-03-21 00:30 UTC
Bug has been introduced when upgrading from 1.0.1 to 1.0.3.

A WButton triggered from a WDialog does not run its action if it has an Ajax target set.

The WButton action is not firing because it does not think it was pressed in the `handleRequest` method.

I’ve attached the HAR file for the Ajax POST.
[HAP Issue.zip](https://github.com/BorderTech/wcomponents/files/181578/HAP.Issue.zip)

The request sent the following for the button:
`wc_ajax=_2d0b1a0a1b1a6a1a1c0b0-dlg-_0a8b0`

`WButton.handleRequest()` is checking the following:
`String requestValue = request.getParameter(getId());`
`boolean pressed = "x".equals(requestValue);`

It looks like the Java code might be out of sync with the client side code.

@marksreeves @jonathanaustin

**Comment by marksreeves** [comment] 2016-03-21 00:41
I believe this issue was fixed in release 1.0.4 by pull #390. I will investigate further.

**Comment by marksreeves** [comment] 2016-03-21 00:41
Closed in error by missing the "Commont" button.

**Comment by marksreeves** [comment] 2016-03-21 00:54
OK, We have a conflation of two issues here.

1. There was a bug in 1.0.3 which broke existing functionality in which opening a WDialog using its "immediate" WButton could tigger the Action on that WButton. This but was fixed in 1.0.4.
2. If an "immediate" WButton child of a WDialog is _also_ a trigger for another WAjaxControl the Action on that button _is_ triggered but the additional (non-dialog) ajax target(s) are not updated. 

  This is by design:a button used to open a WDialog must not _also_ update components in the current view _outside_ of that WDialog. This is because the form outside of the dialog is made unavailable to users and therefore the changes _may never_ be made apparent to the user.

Since item (1) is fixed and item (2) never worked I have to assume the reported issue relates to (1) and is therefore fixed.

**Comment by Joshua-Barclay** [comment] 2016-03-21 01:18
Misunderstanding of what's happening - reopened.

**Closed** 2016-03-21 03:54 UTC
Labels: bug
