### ISSUE TITLE
Mandatory indicator is placed too far from label

### ISSUE THREAD

**Issue by Likhasinh** [BorderTech/wcomponents#1471] opened 2018-03-05 21:46 UTC
Mandatory field is placed too far from the field label (aligns to the end of the hint text) when field layout is stacked (as a default) and hint text is 'long-ish'.

**Comment by marksreeves** [comment] 2018-03-19 06:30
This is now an implementation issue. The core theme has minimal styling around the position of the mandatory indicator which will resolve the root cause of this issue - resolved in #1475.

**Closed by marksreeves** 2018-03-19 06:30 UTC
Labels: accessibility, enhancement, theme only
